### ISSUE TITLE
Do we have data that's not on the ISBE site?

### ISSUE THREAD

**Issue by fgregg** [datamade/illinois-sunshine#100]
For some committees, we seem to have more detailed info on campaigns than is available on the ISBE site.

For example, compare http://illinoissunshine.org/committees/26221/ to http://www.elections.il.gov/CampaignDisclosure/CommitteeDetail.aspx?id=26221 where there are only pdf's available?

cc @sarahbrune

If this is so, we should advertise this as a benefit of illinoissunshine.org

**Comment by sarahbrune** [comment]
we definitely do in that we aggregate all of the committee data and show the funds available and funds over time in a much more digestible way. Also, if you're on the SBOE sight, finding historical data about the committees is very difficult because you would have to click back through the quarterlies and add everything up yourself...

**Comment by fgregg** [comment]
I know that we are showing views of the data that's not available on the
ISBE. And that's the main thing that makes illinoissunshine awesome.
However, I think that we may also have data that's only available as PDFs
on the ISBE site.

On Wed, Sep 16, 2015 at 2:27 PM, sarahbrune <notifications@github.com>
wrote:

> we definitely do in that we aggregate all of the committee data and show
> the funds available and funds over time in a much more digestible way.
> Also, if you're on the SBOE sight, finding historical data about the
> committees is very difficult because you would have to click back through
> the quarterlies and add everything up yourself...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/illinois-sunshine/issues/100#issuecomment-140858804>
> .
>



-- 
773.888.2718
