### ISSUE TITLE
Possible fuzzy search issue

### ISSUE THREAD

**Issue by sarahbrune** [datamade/illinois-sunshine#106]
Hey all - I just got this email from a guy (I don't know him) regarding IL Sunshine. Any thoughts on why this issue is presenting?

Hi,

I like the look and feel of your Illinois Sunshine database but I have encountered a problem doing a basic search. If I start on your homepage (http://illinoissunshine.org/) and search the term "More" I get "No results found for 'More' "

If I go to the State Board of Elections website and do the same search, it pulls up a list of names including "More" and I can select the one I want "Donna More" and it finds 128 records (a few pasted below). Donna More is a current Cook County State's Attorney candidate so there should be plenty of action involving her name.

This seems like a problem. Is it? I know that I can't currently use your database to find things that are easily found on the State website.

Thank you,
Jolyon Ticer-Wurr

Screen shot of his attachment:
<img width="1236" alt="screen shot 2015-11-05 at 9 44 29 pm" src="https://cloud.githubusercontent.com/assets/14282538/10988912/7bb5d884-8406-11e5-9d9c-f36b2ed2c488.png">

**Comment by evz** [comment]
Huh, OK, well looks like our search engine treats "more" as a stop word. These are words that occur really often in a given language and are generally just noise. If you search for "Donna More" [she comes up](http://illinoissunshine.org/committees/31632/) (but only because of the "Donna" part). I'll get in there and take out "more" and see if there are any other stop words that might be problematic.

**Comment by evz** [comment]
@sarahbrune I updated the stop words we're using for the full text search. I took out "more" as well as a few others which seemed like they might be problematic (like "now").

**Comment by evz** [comment]
Oh, I guess I forgot to mention that this means that searching for "more" will now return results.

**Comment by sarahbrune** [comment]
Thanks!!

**Comment by sarahbrune** [comment]
A related question - It's almost impossible to search for AT&T...maybe it's the ampersand? This week one of the largest donations was made by "AT&T Services, Inc. on behalf of AT&T Illinois" but when you search for them nothing comes up

![screen shot 2015-11-06 at 10 32 13 am](https://cloud.githubusercontent.com/assets/14282538/11002314/a97aa234-8471-11e5-93a3-fab19dd8579d.png)

**Comment by evz** [comment]
Ahh! So obvious. I'll fix that.

**Comment by evz** [comment]
OK, that took a bit more effort that I thought it would but one can now search for AT&T and get what you'd expect.

**Comment by sarahbrune** [comment]
YAY Thank you!
