### ISSUE TITLE
Download Issue w.Citizens for Rauner

### ISSUE THREAD

**Issue by sarahbrune** [datamade/illinois-sunshine#109]
Karen Yourish from NYT called, and she said she gets an error message when she tries to download "all donations" from Citizens for Rauner. She doesn't get this error on other committees. Screen shots attached 
![screen shot 2015-11-13 at 10 00 35 am](https://cloud.githubusercontent.com/assets/14282538/11150978/4d870042-89f0-11e5-88d3-3dbdbb2ad7b7.png)
![screen shot 2015-11-13 at 10 00 53 am](https://cloud.githubusercontent.com/assets/14282538/11150979/4d8809b0-89f0-11e5-9e8c-7710a5fb4d95.png)

**Comment by derekeder** [comment]
@sarahbrune we'll look into it!

**Comment by sarahbrune** [comment]
Thanks!

**Comment by sarahbrune** [comment]
Any movement on this? I want to get back to the NYT reporter

**Comment by sarahbrune** [comment]
I still get the error message

**Comment by evz** [comment]
@sarahbrune Jeez, give me a second ;P It should be restarted now.

**Comment by sarahbrune** [comment]
yaaaay! :smile:
