### ISSUE TITLE
zero funds for committees

### ISSUE THREAD

**Issue by derekeder** [datamade/illinois-sunshine#13]
On the committee listing page, some of the funds are displaying as $0. 

This is the logic that's being used to calculate that number for each committee:

```sql
(SUM(receipts.amount) + MAX(filings.end_funds_available) + MAX(filings.total_investments) - MAX(filings.total_debts)) AS total,
```
https://github.com/datamade/illinois-sunshine/blob/master/etl.py#L722

We either need to handle nulls in this query, or set the default value in the table to 0. @evz thoughts?

**Comment by evz** [comment]
We can just wrap each of the numbers in a [``COALESCE``](http://www.postgresql.org/docs/9.4/static/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL) that defaults it them to 0.
