### ISSUE TITLE
Make distinction between when donations / expenses are reported and when they are received / expended

### ISSUE THREAD

**Issue by evz** [datamade/illinois-sunshine#21]
It seems like we are sorting the query on the home page by when the donations are reported (or when the filing was made) but we are displaying when the committee reported having received the donation: 

![screenshot from 2015-07-06 09 45 47](https://cloud.githubusercontent.com/assets/551491/8524958/cf6de154-23c3-11e5-8761-8c4880a129c8.png)

 ... whereas the donations page seems to be sorting the query by when the committee reported receiving the donation which is also how the table seems to be sorted.

![screenshot from 2015-07-06 09 49 17](https://cloud.githubusercontent.com/assets/551491/8525060/4c3bc462-23c4-11e5-9972-69fdebc846ed.png)

I'm not sure which is best. It seems good to highlight recent filings (because otherwise those contributions from May would get buried) but it doesn't really make sense from a users perspective. Maybe we can just show both dates and have a consistent sort (or maybe a way for the user to sort).

**Comment by derekeder** [comment]
Let's stick with sorting by and displaying just when it was received.

**Comment by evz** [comment]
This one was fixed when I fixed the slow query on the home page. 75f535cb6221686eadc0da3415efcc82793f24b0
