### ISSUE TITLE
Can we show purpose of expenditures?

### ISSUE THREAD

**Issue by fgregg** [datamade/illinois-sunshine#32]
They seem to be in the data : http://elections.illinois.gov/CampaignDisclosure/ItemizedExpend.aspx?FiledDocID=321322&ExpenditureType=Expenditures&Archived=True&OrderBy=LastorOnlyName-AtoZ&ItemizedExpendFrom=D2Semi.aspx

**Comment by evz** [comment]
This info is on the expenditure detail pages but I think we can bring it out front a bit more.

**Comment by derekeder** [comment]
Done with #32
