### ISSUE TITLE
Email subscription link broken

### ISSUE THREAD

**Issue by michaelcgorman** [datamade/illinois-sunshine#52]
When I click the email subscription link at the bottom of a page, I'm redirected to http://visitor.r20.constantcontact.com/error_general.jsp and shown this error:
![screen shot 2015-08-04 at 09 23 20](https://cloud.githubusercontent.com/assets/313667/9062879/8daa8e9c-3a8a-11e5-8e4e-90eff0a04452.png)

**Comment by derekeder** [comment]
@michaelcgorman thanks for catching that! Fixed.
