### ISSUE TITLE
fix twitter meta desc

### ISSUE THREAD

**Issue by cathydeng** [datamade/illinois-sunshine#53]

**Comment by derekeder** [comment]
This may have been fixed here: https://github.com/datamade/illinois-sunshine/commit/5bc06de3164be9560d538ad524051540fbe23495

Can you confirm?

**Comment by cathydeng** [comment]
hm maybe twitter is caching the information or something, just noticed that ppl tweeting from hack night had cards that looked like this:

<img width="522" alt="screen shot 2015-08-04 at 7 36 56 pm" src="https://cloud.githubusercontent.com/assets/1406537/9076800/96192766-3aec-11e5-8ce4-f333b0cc1a89.png">

**Comment by cathydeng** [comment]
it's working fine on https://cards-dev.twitter.com/validator
