### ISSUE TITLE
Multiple, non amending, A1s

### ISSUE THREAD

**Issue by fgregg** [datamade/illinois-sunshine#73]
This committee has two a1 for the same period. http://www.elections.il.gov/CampaignDisclosure/CommitteeDetail.aspx?id=31668

Each A1 has only a single donation in it, but they are from different donors.

We are only showing one donor http://www.illinoissunshine.org/committees/31668/

Seems like we should be showing both donors?

It kind of looks like he is filing a separate A1 for each donation, as the donations come in. This is definitely nonstandard use, but if it's happening once, it's happening more than once.

**Comment by evz** [comment]
A-1s need to be filed within 5 days of a donation that is over $1,000. So, that means that there are usually several of these that come in between a given quarterly filing. See, for example Rauner: http://www.elections.il.gov/CampaignDisclosure/CommitteeDetail.aspx?id=25185

A spot check of Rauner's committee on Illinois Sunshine reveals that we are getting all of those A-1s even when there are many in between quarterlies. 

The code that attempts to reconcile all of this is here: https://github.com/datamade/illinois-sunshine/blob/master/etl.py#L642-L670

**Comment by evz** [comment]
The Derek Bagley donation is definitely getting lost when we make that materialized view. It exists in the raw file that we are downloading from the Board of Elections, and in the full, non-condensed version of the receipts table. Because of that, you can actually see it on the site if you know the ID: http://illinoissunshine.org/contributions/4298267/

**Comment by fgregg** [comment]
So the Rauner donations are different because they are being filed *after* the end of the reporting period so I think they are being picked up in the first select of that union of selects. 

The Harishi filings are being filed within the reporting period and they are being dealt with in the second select. I think they are being clobbered by that `DISTINCT ON`

**Comment by evz** [comment]
Solved while waiting for a plane
